### ISSUE TITLE
VisualComponent class refactoring

### ISSUE THREAD

**Issue by VictorJorgeFGA** [VictorJorgeFGA/8Ball#13]
### Description:

For now VisualComponent class has some undesired behaviors: 
- It doesn't display its objects which doesn't have any texture;
- It doesn't offer a way to make color areas (rectangle with a specific color);
- It spends resources rendering unchanged informations multiple times;
- It requires its specializations to set SCREEN object as parent manually;
- It allow negative dimension (width, height) values;
- It doesn't allow direct instance (only specializations can be declared).

### Tasks:
- [x] Create "color only mode" (allowing objects to be displayed with no texture by painting their texture area with a specified color)
- [ ] Create state system in order to avoid redundant rendering (render only objects that have changed their state)
- [x] Allow direct instance and provide security constraints (forbidding creating a VisualComponent before initialization)
- [x] Forbid setting negative dimensions (with, height)
